apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmm-monit
  labels:
    app: dmm-monit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmm-monit
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dmm-monit
    spec:
      containers:
        - name: dmm-monit
          image: aaarora/dmm-monit:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
      dnsPolicy: Default
      tolerations:
      - key: "nautilus.io/noceph" 
        operator: "Exists"
        effect: "NoSchedule"
      - key: "nautilus.io/ceph" 
        operator: "Exists"
        effect: "NoSchedule"
      - key: "nautilus.io/testing" 
        operator: "Exists"
        effect: "NoSchedule"
      - key: "nautilus.io/stashcache"
        operator: "Exists"
        effect: "NoSchedule"
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
